export enum LIBRARY_ENUM {
    MY_LIBRARY = 'MY_LIBRARY',
    SUBSCRIBERS_LIBRARY = 'SUBSCRIBERS_LIBRARY',
    VILIYO_LIBRARY = 'VILIYO_LIBRARY'
}

export enum LIBRARY_MEDIA_ENUM {
    PDF = 'PDF',
    DOC_DOCX = 'DOC_DOCX',
    XLS_XLSX = 'XLS_XLSX',
    VIDEO = 'VIDEO',
    AUDIO = 'AUDIO',
    TXT = 'TXT'
}

export enum LIBRARY_TAGS_ENUM {
    BEHAVIOURAL = 'BEHAVIOURAL',
    FUNCTIONAL = 'FUNCTIONAL',
    TECHNICAL = 'TECHNICAL',
    COMPLIANCE = 'COMPLIANCE',
    OTHER = 'OTHER'
}