export enum STATUS {
  'REGISTERED' = 'REGISTERED',
  'SUBMITTED' = 'SUBMITTED',
  'CONFIRMED' = 'CONFIRMED',
  'VALIDATED' = 'VALIDATED',
  'QUARANTINED' = 'QUARANTINED',
  'BANNED' = 'BANNED',
  'REVIEWED' = 'REVIEWED'
}

export enum PENDING_TASKTYPE {
  NEW_QUERY_TO_TRAINER = 'NEW QUERY TO TRAINER',
  ADD_PARTICIPANT_TO_PROGRAM = 'ADD PARTICIPANT TO IN NEW PROGRAM',
  PENDING_CLIENT_ONBOARD = 'PENDING_CLIENT_ONBOARD',
  'VALIDATED' = 'VALIDATED',
  'QUARANTINED' = 'QUARANTINED',
  'BANNED' = 'BANNED',
  'REVIEWED' = 'REVIEWED'
}